{% set name = "junifer-data" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/junifer_data-{{ version }}.tar.gz
  sha256: 84b6f3de8ad2456561ba3dbb8b22e356f478a5eb06df6fd552470f33f2753e5e

build:
  entry_points:
    - junifer-data = junifer_data._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.3,<8.2
    - datalad >=1.0.0,<1.2.0
    - lazy_loader ==0.4

test:
  imports:
    - junifer_data
  commands:
    - junifer-data --help
    # note: https://github.com/conda-forge/staged-recipes/pull/28864#discussion_r2285844044
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/juaml/junifer-data-client
  summary: Python client for junifer-data
  license: AGPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/juaml/junifer-data-client

extra:
  recipe-maintainers:
    - synchon
